# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '200609' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ARCL'
  # Pods for 200609

  target '200609Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '200609UITests' do
    # Pods for testing
  end

end
